"""Boundary bridge for B2's real webhook and a durable synthetic directory."""
from radar.ports.types import ConditionalConflict, OutboxEntry, Receipt
from .sqlite import digest, stamp

try:
    from radar.adapters.telegram import consent
except ImportError:  # A3's isolated pre-consent base; integration uses B's module.
    consent = None


class Directory:
    def __init__(self, store):
        self.store = store

    def enroll_synthetic(self, numeric_id, *, owner_ref, actor_ref, role='owner'):
        if type(numeric_id) is not int or role not in ('owner','collaborator'):
            raise ValueError('synthetic_directory_entry_required')
        with self.store.transaction():
            self.store.db.execute('INSERT OR IGNORE INTO owners(owner) VALUES(?)',(owner_ref,))
            self.store.db.execute('INSERT OR REPLACE INTO actors VALUES(?,?,?)',(owner_ref,actor_ref,0 if consent else 1))
            self.store.db.execute('INSERT INTO directory(id,owner,actor,role) VALUES(?,?,?,?)',(numeric_id,owner_ref,actor_ref,role))

    def get(self, numeric_id):
        row = self.store.db.execute('SELECT owner,actor,role,consent_version,consent_at FROM directory WHERE id=?',(numeric_id,)).fetchone()
        if not row:
            return None
        return dict(zip(('owner_ref','user_ref','role','consent_version','consent_accepted_at'),row))

    def by_actor(self, actor_ref):
        rows = self.store.db.execute('SELECT id FROM directory WHERE actor=?',(actor_ref,)).fetchall()
        if len(rows) != 1:
            raise ConditionalConflict('ambiguous_or_unknown_directory_actor')
        return self.get(rows[0][0])

    def accepted(self, user):
        return consent.has_consent(user) if consent else True

    def accept_consent(self, user_ref, version, accepted_at, idempotency_keys):
        user = self.by_actor(user_ref)
        if consent and version != consent.CONSENT_VERSION:
            raise ConditionalConflict('wrong_consent_version')
        with self.store.transaction():
            if any(self.store.db.execute('SELECT 1 FROM ignored WHERE ref=?',(key,)).fetchone() for key in idempotency_keys):
                return False
            for key in idempotency_keys:
                self.store.db.execute('INSERT INTO ignored VALUES(?)',(key,))
            self.store.failpoint('after_consent_receipt')
            self.store.db.execute('UPDATE directory SET consent_version=?,consent_at=? WHERE owner=? AND actor=?',(version,stamp(accepted_at),user['owner_ref'],user_ref))
            self.store.db.execute('UPDATE actors SET enabled=1 WHERE owner=? AND actor=?',(user['owner_ref'],user_ref))
            self.store.db.execute('INSERT INTO consent_history(owner,actor,version,accepted) VALUES(?,?,?,?)',(user['owner_ref'],user_ref,version,stamp(accepted_at)))
        return True


class TelegramBridge:
    def __init__(self, store, directory):
        self.store, self.directory = store,directory
        self.last_accepted = None

    def commit(self, receipt, command, outbox):
        user = self.directory.by_actor(command['telegram_user_ref'])
        if user['owner_ref'] != outbox['owner_ref'] or not self.directory.accepted(user):
            raise ConditionalConflict('directory_owner_or_consent')
        # IDs/deadline generated by B2 are not semantic intent. For callbacks,
        # update_id is another transport receipt, not the callback's identity.
        semantic = {k:v for k,v in command.items() if k != 'update_id'}
        keys = tuple(receipt['idempotency_keys'])
        self.last_accepted = self.store.accept_command(
            owner_ref=user['owner_ref'],
            receipt=Receipt('telegram',keys[0],digest(semantic),keys[1:]),
            command=outbox,outbox=OutboxEntry(outbox,'commands.fifo',user['owner_ref']),
        )
        return not self.last_accepted.replayed


class Idempotency:
    """Update IDs belong to one synthetic bot instance, as in Telegram."""
    def __init__(self, store):
        self.store = store

    def seen(self, key):
        return bool(self.store.db.execute('SELECT 1 FROM ignored WHERE ref=?',(key,)).fetchone() or
                    self.store.db.execute('SELECT 1 FROM receipts WHERE channel=\'telegram\' AND ref=?',(key,)).fetchone())

    def remember(self, key):
        self.store.db.execute('INSERT OR IGNORE INTO ignored VALUES(?)',(key,))


class NoInvites:
    def redeem(self, code_sha256, telegram_user_id, now):
        return False
